com:
  ashokit:
    address:
      cityName: Hyderabad
      doorNo: 1-2-3
      streetName: Ameerpet
    streetName: Ameerpet
    billAmount: 25000
    colors:
     - Orange
     - Yellow
     - Red
     - blue
    customerId: AIT234
    customerName: Suresh
empDesignation: SoftwareEngineer
empId: AIT123
empName: Mahesh
empSalary: 25000
spring:
  application:
    name: FirstSpringBootApplication
  banner:
    location: classpath:banner.txt